name: stripe_new
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.1.3


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_stripe: 11.0.0
  http: ^1.2.2
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  retrofit: ^4.0.1
  dio: ^5.4.2+1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  equatable: ^2.0.5
  flutter_dotenv: ^5.2.1
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator:
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  build_runner: ^2.1.7
  freezed: ^2.1.0


flutter:
  uses-material-design: true
  assets:
    - .env

